import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"OUI FM Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/oui-fm-reggae.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ouifmganja.ice.infomaniak.ch/ouifmganja-128.mp3",
            active: true,
        },
        {
            name:"Mashup Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/mashup-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ais-edge08-live365-dal02.cdnstream.com/a00564",
            active: false,
        },
        {
            name:"La Grosse Radio Reggae Francia",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/la-grosse-radio-reggae-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://ice2.lagrosseradio.info/lagrosseradio-reggae-192.mp3",
            active: false,
        },
        {
            name:"FunX Rotterdam Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/funx-rotterdam-reggae-reggae.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://icecast.omroep.nl/funx-reggae-bb-mp3",
            active: false,
        },
        {
            name:"Reggaetune FM",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/reggaetune-fm-reggae-dub.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bluford.torontocast.com:8067/stream",
            active: false,
        },
        {
            name:"Reggae Starz Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-starz-radio.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://streams.radio.co/s07aafdd25/listen",
            active: false,
        },
        {
            name:"Jammin Vibez Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/jammin-vibez-radio.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://mediacp.myautodj.com:8010/stream",
            active: false,
        },
        {
            name:"Positive Radio Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/positive-radio-reggae.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://server.radiostreaming.com.ar/8066/stream",
            active: false,
        },
        {
            name:"Perfect Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/perfect-reggae-1.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://n02.radiojar.com/ezs0qr9m4qruv",
            active: false,
        },
        {
            name:"Reggae King Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-king.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://198.178.123.17:10196/stream/1/",
            active: false,
        },
        {
            name:"Jumble FM Urban Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/jumble-fm-urban-reggae-reggae-urban.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://ca4.rcast.net:8048/;",
            active: false,
        },
        {
            name:"Planeta Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/planeta-reggae.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://servidor23.brlogic.com:7142/live",
            active: false,
        },
        {
            name:"Reggae Paradise",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-paradise.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://reggae-paradise.stream.laut.fm/reggae-paradise",
            active: false,
        },
        {
            name:"Deutscher Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/deutscher-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://deutscher-reggae.stream.laut.fm/deutscher-reggae",
            active: false,
        },
        {
            name:"Reggae Mix Station",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-mix-stations.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://france1.coollabel-productions.com:8142/;",
            active: false,
        },
        {
            name:"Exclusively Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/exclusively-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streaming.exclusive.radio/er/reggae/icecast.audio",
            active: false,
        },
        {
            name:"bigFM Reggae Vibez",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bigfm-dancehall-reggae-vibez-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://streams.bigfm.de/bigfm-reggaevibes-128-mp3",
            active: false,
        },
        {
            name:"Generations Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/generation-reggae.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://generations-caraibes.ice.infomaniak.ch/generations-caraibes-high.mp3",
            active: false,
        },
        {
            name:"Rastamusic",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/rastamusic-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ais.rastamusic.com/rastamusic.mp3",
            active: false,
        },
        {
            name:"UrbanMelodyFM",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/soulfully-smooth-en-urbanmelodyfm-en-tunein.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://78.129.224.21:18077/;",
            active: false,
        },
        {
            name:"RadioArt Roots Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://live.radioart.com/fRoots_reggae.mp3",
            active: false,
        },
         {
            name:"Dj Papa Lion",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/dj-papa-lion.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://dj-papa-lion.stream.laut.fm/dj-papa-lion",
            active: false,
        },
         {
            name:"Roots Legacy Radio Lille",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/roots-legacy-radio-dub-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://rootslegacy.fr:8080/stream/1/",
            active: false,
        },
        {
            name:"007FM",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/007fm-reggae-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ruffneck-smille.stream.laut.fm/ruffneck-smille",
            active: false,
        },
        {
            name:"Reggae Empire Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/screenshot_2019-09-22-escucha-a-reggae-empire-radio-en-tunein1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://192.99.8.192:3106/stream",
            active: false,
        },
        {
            name:"Bubble-Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bubble-radio-reggae-dub.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bubble-radio.stream.laut.fm/bubble-radio",
            active: false,
        },
        {
            name:"PARTY VIBE RADIO Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-2.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://94.130.242.5:8000/stream/1/",
            active: false,
        },
        {
            name:"Reggae Showtime Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/regae-showtime-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://eu1.fastcast4u.com:2670/showtime",
            active: false,
        },
        {
            name:"Big Up",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/big-up-dub-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://big-up.stream.laut.fm/big-up",
            active: false,
        },
        {
            name:"Raggakings",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/raggakings-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://raggakings.radio:8443/stream.ogg",
            active: false,
        },
        {
            name:"Webadub Hot Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/webadub-hot-radio-dub-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://listen.radioking.com/radio/119437/stream/158899",
            active: false,
        },
        {
            name:"ReggaeTrade FM Suiza",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/1-fm-reggaetrade-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
        {
            name:"Reggae Connection",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/reggae-connection-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-11.zeno.fm/fqwxrqhtknruv",
            active: false,
        },
        {
            name:"GotRadio Reggae Rasta",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-3.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://206.217.213.236:8470/",
            active: false,
        },
        {
            name:"Rouge Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/rouge-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://rouge-reggae.ice.infomaniak.ch/rouge-reggae-128.mp3",
            active: false,
        },
        {
            name:"Hype Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/hype-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s31.myradiostream.com:9882/stream/1/",
            active: false,
        },
        {
            name:"Reggae Ambassadors",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-ambassadors.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-15.zeno.fm/mvtbzpenhzzuv",
            active: false,
        },
        {
            name:"101 ru  Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-4.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://pub0302.101.ru:8443/stream/pro/aac/64/44",
            active: false,
        },
         {
            name:"Open Fm Polish Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/ope-fm-polish-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.open.fm/22",
            active: false,
        },
         {
            name:"Reggaeone",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggaeone.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://reggaeone.stream.laut.fm/reggaeone",
            active: false,
        },
         {
            name:"Reggaeneracija Montenegro",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggaeneracija-montenegroc.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://player.reggaeneracija.me/proxy/reggaeneracija/stream",
            active: false,
        },
         {
            name:"Reggae Mistico",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-mistico.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-34.zeno.fm/nt3g6u0pe6quv",
            active: false,
        },
         {
            name:"Fyah 105",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fiah-105-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://live.str3am.com:9210/live",
            active: false,
        },
        {
            name:"FIP autour du reggae",
            artist: "Ska & Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fip-autour-du-reggae-reggae-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.radiofrance.fr/fipreggae-midfi.mp3",
            active: false,
        },
        {
            name:"CALM RADIO - Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/calm-radio-reggae-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.calmradio.com:18928/stream/1/",
            active: false,
        },
        {
            name:"Sensimedia - Dancehall Radio",
            artist: "Reggae & Dancehall",
            cover: "https://manuappshome.files.wordpress.com/2019/09/sensimedia-roots-radio-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://janus.shoutca.st:8233/stream/0/",
            active: false,
        },
        {
            name:"24-7 Niche Radio - Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/24-7-niche-radio-reggae-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ssl.shoutcaststreaming.us:8045/;",
            active: false,
        },
        {
            name:"Allzic Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/allzic-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://allzic43.ice.infomaniak.ch/allzic43.mp3",
            active: false,
        },
        {
            name:"NRJ REGGAE",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/nrj-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://scdn.nrjaudio.fm/adwz1/fr/30075/mp3_128.mp3",
            active: false,
        },
        {
            name:"The Dub Lounge",
            artist: "Reggae & Lounge",
            cover: "https://manuappshome.files.wordpress.com/2019/09/the-dub-lounge-reggae-chillout.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://144.217.129.213:8311/stream/1/",
            active: false,
        },
        {
            name:"RMF Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/rmf-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://31.192.216.7/REGGAE",
            active: false,
        },
        {
            name:"Your Flava Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/your-flava-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://17003.live.streamtheworld.com/SP_R3137032_SC",
            active: false,
        },
        {
            name:"ReGGae 141 Nueva York",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/reggae-141-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://hestia2.cdnstream.com/1301_128",
            active: false,
        },
        {
            name:"Miled Music Reggae Mexico",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/miled-music-reggae-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://192.99.34.205:8143/stream",
            active: false,
        },
        {
            name:"Ras Reggae Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/ras-reggae-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-25.zeno.fm/bbh6u7w8gwzuv.acc",
            active: false,
        },
        {
            name:"OpenFM - 500 Reggae Hits",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/openfm-500-reggae-hits-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.open.fm/30",
            active: false,
        },
        {
            name:"Allenbach Rock Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/allenbach-rock-radio-country-baladas.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://allenbach-rock-radio.stream.laut.fm/allenbach-rock-radio",
            active: false,
        },
        {
            name:"101-ru  Country Moscu",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/101-ru-country-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pub0101.101.ru:8000/stream/pro/aac/64/78",
            active: false,
        },
        {
            name:"P10 Country Lillehammer Noruega",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/p10-country-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://p10.p4groupaudio.com/P10_MM",
            active: false,
        },
        {
            name:"Doppelstopp Radio Gummersbach",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/doppelstop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://doppelstopp.stream.laut.fm/doppelstopp",
            active: false,
        },
        {
            name:"CFRY Radio 920 AM Portage la Prairie",
            artist: "Pop Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/cfry-radio-920-am-country-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://chi-live3-ais-relay1.leanstream.co/goldenwest/CFRYAM.stream",
            active: false,
        },
        {
            name:"Radio CJ1150",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/cj-1150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://goldenwest.leanstream.co/CJSLAM-MP3",
            active: false,
        },
        {
            name:"AM 1190 Radio Weyburn Canada",
            artist: "Pop Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/am-1190-radio-country-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://goldenwest.leanstream.co/CFSLAM-MP3",
            active: false,
        },
        {
            name:"107.7 The Wolf. Toledo EE.UU",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/107-7-the-wolf-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ice9.securenetsystems.net/WPFX",
            active: false,
        },
        {
            name:"Country Radio Praga Rep. Checa",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/country-generico-3.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://icecast4.play.cz/country128.mp3",
            active: false,
        },
        {
            name:"Radio Pauline Alemania",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/pauline-blues-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pauline.stream.laut.fm/pauline",
            active: false,
        },
        {
            name:"Midlands 103 Irlanda",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/midlands-103-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://n20a-eu.rcs.revma.com/tq45ca1vftzuv",
            active: false,
        },
        {
            name:"Sound Radio Heppenheim Alemania",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/sound-radio-pop-oldies.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sound.stream.laut.fm/sound",
            active: false,
        },
         {
            name:"Ostseelieder Radio Alemania",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/ostseelieder-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ostseelieder.stream.laut.fm/ostseelieder",
            active: false,
        },
         {
            name:"Notenkiste Radio Alemania",
            artist: "Country Rock",
            cover: "https://manuappshome.files.wordpress.com/2019/09/notenkiste-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://notenkiste.stream.laut.fm/notenkiste",
            active: false,
        },
         {
            name:"Hall of Music Bremen Alemania",
            artist: "Pop Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/hall-of-music-country-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://hallofmusic.stream.laut.fm/hallofmusic",
            active: false,
        },
         {
            name:"WDVX The Dove 89.9 FM",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/the-dove-89-7-fm-clc3a1sica.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://wdvx.streamguys1.com/live",
            active: false,
        },
         {
            name:"Wide Line Country",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/wide-line-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sr9.inmystream.info:8112/stream",
            active: false,
        },
         {
            name:"Kdub Hit Country",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/kdub-hit-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://kdub-rebelmedia.radioca.st/stream",
            active: false,
        },
         {
            name:"KG Country 1380 AM",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/kg-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://playerservices.streamtheworld.com/api/livestream-redirect/KHWKAM.mp3",
            active: false,
        },
         {
            name:"Birdhill Radio Irlanda",
            artist: "Pop Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/birdhill-radio-country-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://abacus.hostingenergy.com:8000/stream/1/",
            active: false,
        },
         {
            name:"CALM RADIO - Country Classics",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/calm-radio-country-classics-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.calmradio.com:13528/stream/1/",
            active: false,
        },
         {
            name:"Calm Country Markham Canada",
            artist: "Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/calm-radio-calm-country-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.calmradio.com:13428/stream/1/",
            active: false,
        },
         {
            name:"Christian Country Channel Essen",
            artist: "Christian Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/christian-country-channel-country-mc3basica-cristiana.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://christian-country-channel.stream.laut.fm/christian-country-channel",
            active: false,
        },
         {
            name:"WUMB Radio Christmas Music Boston",
            artist: "Christmas Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/wumb-radio-christmas-music-country-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://wumb.streamguys1.com/wumb919hol",
            active: false,
        },
         {
            name:"BigR - Christmas Country",
            artist: "Christmas Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bigr-christmas-country-country.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bigrradio.cdnstream1.com/5191_128",
            active: false,
        },
        {
            name:"181.fm - Christmas Kountry",
            artist: "Christmas Country",
            cover: "https://manuappshome.files.wordpress.com/2019/09/country-generico-5.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://uplink.duplexfx.com:8084/",
            active: false,
        },
    ];
}

export default chillHop;

