import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"OUI FM Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/oui-fm-reggae.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ouifmganja.ice.infomaniak.ch/ouifmganja-128.mp3",
            active: true,
        },
        {
            name:"La Grosse Radio Reggae Francia",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/la-grosse-radio-reggae-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://ice2.lagrosseradio.info/lagrosseradio-reggae-192.mp3",
            active: false,
        },
        {
            name:"FunX Rotterdam Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/funx-rotterdam-reggae-reggae.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://icecast.omroep.nl/funx-reggae-bb-mp3",
            active: false,
        },
        {
            name:"Reggaetune FM",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/reggaetune-fm-reggae-dub.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bluford.torontocast.com:8067/stream",
            active: false,
        },
        {
            name:"Reggae Starz Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-starz-radio.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://streams.radio.co/s07aafdd25/listen",
            active: false,
        },
        {
            name:"Jammin Vibez Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/jammin-vibez-radio.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://mediacp.myautodj.com:8010/stream",
            active: false,
        },
        {
            name:"Positive Radio Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/positive-radio-reggae.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://server.radiostreaming.com.ar/8066/stream",
            active: false,
        },
        {
            name:"Perfect Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/perfect-reggae-1.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://n02.radiojar.com/ezs0qr9m4qruv",
            active: false,
        },
        {
            name:"Reggae King Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-king.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://198.178.123.17:10196/stream/1/",
            active: false,
        },
        {
            name:"Jumble FM Urban Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/jumble-fm-urban-reggae-reggae-urban.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://ca4.rcast.net:8048/;",
            active: false,
        },
        {
            name:"Planeta Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/planeta-reggae.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://servidor23.brlogic.com:7142/live",
            active: false,
        },
        {
            name:"Reggae Paradise",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-paradise.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://reggae-paradise.stream.laut.fm/reggae-paradise",
            active: false,
        },
        {
            name:"Deutscher Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/deutscher-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://deutscher-reggae.stream.laut.fm/deutscher-reggae",
            active: false,
        },
        {
            name:"Reggae Mix Station",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-mix-stations.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://france1.coollabel-productions.com:8142/;",
            active: false,
        },
        {
            name:"Exclusively Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/exclusively-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streaming.exclusive.radio/er/reggae/icecast.audio",
            active: false,
        },
        {
            name:"bigFM Reggae Vibez",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bigfm-dancehall-reggae-vibez-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://streams.bigfm.de/bigfm-reggaevibes-128-mp3",
            active: false,
        },
        {
            name:"Generations Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/generation-reggae.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://generations-caraibes.ice.infomaniak.ch/generations-caraibes-high.mp3",
            active: false,
        },
        {
            name:"Rastamusic",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/rastamusic-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ais.rastamusic.com/rastamusic.mp3",
            active: false,
        },
        {
            name:"RadioArt Roots Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://live.radioart.com/fRoots_reggae.mp3",
            active: false,
        },
         {
            name:"Dj Papa Lion",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/dj-papa-lion.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://dj-papa-lion.stream.laut.fm/dj-papa-lion",
            active: false,
        },
         {
            name:"Roots Legacy Radio Lille",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/roots-legacy-radio-dub-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://rootslegacy.fr:8080/stream/1/",
            active: false,
        },
        {
            name:"007FM",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/007fm-reggae-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ruffneck-smille.stream.laut.fm/ruffneck-smille",
            active: false,
        },
        {
            name:"Reggae Empire Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/screenshot_2019-09-22-escucha-a-reggae-empire-radio-en-tunein1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://192.99.8.192:3106/stream",
            active: false,
        },
        {
            name:"Bubble-Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bubble-radio-reggae-dub.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bubble-radio.stream.laut.fm/bubble-radio",
            active: false,
        },
        {
            name:"PARTY VIBE RADIO Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-2.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://94.130.242.5:8000/stream/1/",
            active: false,
        },
        {
            name:"Reggae Showtime Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/regae-showtime-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://eu1.fastcast4u.com:2670/showtime",
            active: false,
        },
        {
            name:"Big Up",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/big-up-dub-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://big-up.stream.laut.fm/big-up",
            active: false,
        },
        {
            name:"Raggakings",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/raggakings-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://raggakings.radio:8443/stream.ogg",
            active: false,
        },
        {
            name:"Webadub Hot Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/webadub-hot-radio-dub-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://listen.radioking.com/radio/119437/stream/158899",
            active: false,
        },
        {
            name:"ReggaeTrade FM Suiza",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/1-fm-reggaetrade-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
        {
            name:"Reggae Connection",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/reggae-connection-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-15.zeno.fm/5419rtbf9yzuv",
            active: false,
        },
        {
            name:"GotRadio Reggae Rasta",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-3.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://206.217.213.236:8470/",
            active: false,
        },
        {
            name:"Rouge Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/rouge-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://rouge-reggae.ice.infomaniak.ch/rouge-reggae-128.mp3",
            active: false,
        },
        {
            name:"Hype Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/hype-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s31.myradiostream.com:9882/stream/1/",
            active: false,
        },
        {
            name:"Reggae Ambassadors",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-ambassadors.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream-15.zeno.fm/mvtbzpenhzzuv",
            active: false,
        },
        {
            name:"101 ru  Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-generico-4.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://pub0302.101.ru:8443/stream/pro/aac/64/44",
            active: false,
        },
         {
            name:"Open Fm Polish Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/ope-fm-polish-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.open.fm/22",
            active: false,
        },
         {
            name:"Reggaeone",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggaeone.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://reggaeone.stream.laut.fm/reggaeone",
            active: false,
        },
         {
            name:"Reggaeneracija Montenegro",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggaeneracija-montenegroc.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://player.reggaeneracija.me/proxy/reggaeneracija/stream",
            active: false,
        },
         {
            name:"Reggae Mistico",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-mistico.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-28.zeno.fm/nt3g6u0pe6quv",
            active: false,
        },
         {
            name:"Fyah 105",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fiah-105-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://listen.radioking.com/radio/459389/stream/514595",
            active: false,
        },
        {
            name:"FIP autour du reggae",
            artist: "Ska & Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/fip-autour-du-reggae-reggae-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://icecast.radiofrance.fr/fipreggae-midfi.mp3",
            active: false,
        },
        {
            name:"CALM RADIO - Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/calm-radio-reggae-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://streams.calmradio.com:18928/stream/1/",
            active: false,
        },
        {
            name:"Sensimedia - Dancehall Radio",
            artist: "Reggae & Dancehall",
            cover: "https://manuappshome.files.wordpress.com/2019/09/sensimedia-roots-radio-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://janus.shoutca.st:8233/stream/0/",
            active: false,
        },
        {
            name:"24-7 Niche Radio - Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/24-7-niche-radio-reggae-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ssl.shoutcaststreaming.us:8045/;",
            active: false,
        },
        {
            name:"Allzic Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/allzic-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://allzic43.ice.infomaniak.ch/allzic43.mp3",
            active: false,
        },
        {
            name:"NRJ REGGAE",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/nrj-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://scdn.nrjaudio.fm/adwz1/fr/30075/mp3_128.mp3",
            active: false,
        },
        {
            name:"The Dub Lounge",
            artist: "Reggae & Lounge",
            cover: "https://manuappshome.files.wordpress.com/2019/09/the-dub-lounge-reggae-chillout.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://176.9.7.145:8311/stream",
            active: false,
        },
        {
            name:"RMF Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/rmf-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://31.192.216.7/REGGAE",
            active: false,
        },
        {
            name:"Your Flava Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/your-flava-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://17563.live.streamtheworld.com/SP_R3137032_SC",
            active: false,
        },
        {
            name:"ReGGae 141 Nueva York",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/reggae-141-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://hestia2.cdnstream.com/1301_128",
            active: false,
        },
        {
            name:"OpenFM - 500 Reggae Hits",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/openfm-500-reggae-hits-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.open.fm/30",
            active: false,
        },
        {
            name:"Scratch Radio Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/scratch-radio-reggae-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://liveonlineradio.net/file/OffAir.mp3",
            active: false,
        },
        {
            name:"King Dub Radio Marsella",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/king-dub-radio-dub-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://london-dedicated.myautodj.com:8862/stream/1/",
            active: false,
        },
        {
            name:"JAHFARI radio Alemania",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/jahfari-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://jahfari.stream.laut.fm/jahfari",
            active: false,
        },
        {
            name:"Sound Chat Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/12/sound-chat-radio.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s2.voscast.com:9059/stream",
            active: false,
        },
        {
            name:"Reggae Ireland Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-ireland-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streamingv2.shoutcast.com/reggaeireland3",
            active: false,
        },
        {
            name:"Reggae Run Tings",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-run-tings.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://reggaeruntings.out.airtime.pro/reggaeruntings_a",
            active: false,
        },
        {
            name:"Voll Fett Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/voll-fett-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://voll-fett-reggae.stream.laut.fm/voll-fett-reggae",
            active: false,
        },
        {
            name:"UK Roots FM 95.4",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/uk-roots-fm-95.4.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://138.201.198.218:8043/stream",
            active: false,
        },
        {
            name:"UFDV Radio Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/ufdv-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://104.194.9.142:8031/live",
            active: false,
        },
        {
            name:"Armageddeonmusik",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/armageddeonmusik.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s5.voscast.com:9263/live",
            active: false,
        },
        {
            name:"REVIVER RADIO",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reviver-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1.wohooo.net:8989/stream",
            active: false,
        },
         {
            name:"Rockerz Islandz",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/rockerz-islandz.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://sv6.vestaradio.com/RockerzIslandz",
            active: false,
        },
         {
            name:"RCI DANCEHALL",
            artist: "Reggae & Dancehall",
            cover: "https://manuappshome.files.wordpress.com/2021/05/rci-dancehall.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://n11a-eu.rcs.revma.com/5stt0yrtpwzuv",
            active: false,
        },
         {
            name:"Identite Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/identite-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://listen.radioking.com/radio/26860/stream/59584",
            active: false,
        },
         {
            name:"ENERGY Reggae Deuchland",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/energy-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://scdn.nrjaudio.fm/adwz1/de/56251/mp3_128.mp3",
            active: false,
        },
         {
            name:"Zanj Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/zanj-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-42.zeno.fm/yx5d62e3wy5tv",
            active: false,
        },
         {
            name:"Classic 21 Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/classic-21-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radios.rtbf.be/wr-eventradio-128.mp3",
            active: false,
        },
         {
            name:"GT Reggae Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/gt-reggae-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://rosetta.shoutca.st:8039/stream",
            active: false,
        },
         {
            name:"Dance FM Live Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/dance-fm-live-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://broadcast.dancefmlive.com/radio/8020/radio.mp3",
            active: false,
        },
         {
            name:"88.2 Reggae Controlla",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/88.2-reggae-controlla.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://108.59.11.81:8235/stream",
            active: false,
        },
         {
            name:"Reggae Mania Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae-mania-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-31.zeno.fm/v1rt509f84zuv",
            active: false,
        },
         {
            name:"Riddim 1 Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/riddim1-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://45.79.186.124/proxy/riddim1radio/stream",
            active: false,
        },
         {
            name:"Krush Yaad Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/krush-yaad-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s3.voscast.com:8469/stream",
            active: false,
        },
         {
            name:"Worl Vybz Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/worl-vybz-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-59.zeno.fm/mkg0g0t2td0uv",
            active: false,
        },
         {
            name:"Ambiance Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/ambiance-reggae-en-directo.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streamingv2.shoutcast.com/Ambiance-Reggae",
            active: false,
        },
         {
            name:"RIE ZAYA REGGAE",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/rie-zaya-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://strm112.1.fm/reggae_mobile_mp3",
            active: false,
        },
         {
            name:"Party Time Radio Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/party-time-radio-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://listen.radioking.com/radio/15154/stream/28256",
            active: false,
        },
         {
            name:"Feel Jah FM",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/feel-jah-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://solid9.streamupsolutions.com:8018/stream",
            active: false,
        },
         {
            name:"Reggae4us Global Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/reggae4us-global-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://station.reggae4us.net:8000/autodj",
            active: false,
        },
         {
            name:"108.9 JAMAICA",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/108.9-jamaica.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://janus.shoutca.st:8139/;",
            active: false,
        },
         {
            name:"Simply Irie Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/simply-irie-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://209.133.216.3:7320/;",
            active: false,
        },
         {
            name:"Big Reggae Mix",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/big-reggae-mix.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ais-sa2.cdnstream1.com/2294_128.mp3",
            active: false,
        },
         {
            name:"Natty Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/natty-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s5.mexside.net:8312/stream",
            active: false,
        },
         {
            name:"Africa N.1 Naija",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/africa-nc2b01-naija.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://african1paris.ice.infomaniak.ch/african1paris-128.mp3",
            active: false,
        },
         {
            name:"Beat FM UK",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/beat-fm-uk.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-27.zeno.fm/eeatkqnpb2zuv",
            active: false,
        },
         {
            name:"Dancehall Link",
            artist: "Reggae & Dancehall",
            cover: "https://manuappshome.files.wordpress.com/2021/05/dancehall-link.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streamer.radio.co/s30d82be5e/listen",
            active: false,
        },
         {
            name:"DASH Kingston",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/dash-kingston.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice55.securenetsystems.net/DASH43",
            active: false,
        },
         {
            name:"Skafari Radio Ravensburg",
            artist: "Reggae & Ska",
            cover: "https://manuappshome.files.wordpress.com/2019/09/skafari-punk-reggae.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://skafari.stream.laut.fm/skafari",
            active: false,
        },
         {
            name:"Bob's SKA Radio",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2019/09/bobs-ska-radio-reggae-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://51.255.235.165:5528/stream",
            active: false,
        },
         {
            name:"Skaworld",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2020/02/skaworld-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://skaworld.stream.laut.fm/skaworld",
            active: false,
        },
         {
            name:"Pinguin Ska",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2020/02/pinguin-ska-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://19293.live.streamtheworld.com/SP_R2292843_SC",
            active: false,
        },
         {
            name:"Miled Music Ska",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2020/02/miled-music-ska-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://192.99.34.205:8458/stream",
            active: false,
        },
         {
            name:"AZ Punk Radio",
            artist: "Ska & Punk",
            cover: "https://manuappshome.files.wordpress.com/2020/02/az-punk-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ais-edge09-live365-dal02.cdnstream.com/a56295",
            active: false,
        },
         {
            name:"Black Cat Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2021/05/black-cat-radio-1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s5.voscast.com:9097/stream",
            active: false,
        },
         {
            name:"Onda Radikal",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/onda-radikal.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-60.zeno.fm/0nbnpzv153duv",
            active: false,
        },
         {
            name:"ALTERNATIVAradioRock",
            artist: "Rock & Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/alternativaradiorock-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://51.161.119.117/8406/stream",
            active: false,
        },
         {
            name:"UbuntuFM Reggae Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/ubuntufm-reggae-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streaming.coollective.nl:8443/UbuntuFMreggae",
            active: false,
        },
         {
            name:"Alpha Boys School Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/alpha-boys-school-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://alphaboys-live.streamguys1.com/alphaboys.mp3",
            active: false,
        },
         {
            name:"Subculture 69 Radio",
            artist: "Reggae & Ska-Punk",
            cover: "https://manuappshome.files.wordpress.com/2020/02/subculture-69-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://144.76.32.5:8000/sbc69r",
            active: false,
        },
         {
            name:"Wolfman Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/wolfman-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://37.59.47.192:8092/;",
            active: false,
        },
         {
            name:"Racketeer Radio",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/racketeer-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ais-edge08-live365-dal02.cdnstream.com/a33242",
            active: false,
        },
         {
            name:"Radio 969",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/radio-969-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://143.208.11.104:8310/;",
            active: false,
        },
         {
            name:"Papas Skakiste007",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2020/02/papas-skakiste007.jpeg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://papasskakiste007.stream.laut.fm/papas_skakiste007",
            active: false,
        },
        {
            name:"Luska Radio",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2020/02/luska-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://luska.stream.laut.fm/luska",
            active: false,
        },
        {
            name:"Riotradio",
            artist: "Ska & Punk",
            cover: "https://manuappshome.files.wordpress.com/2020/02/riotradio-punk-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://riotradio.stream.laut.fm/riotradio",
            active: false,
        },
        {
            name:"Scooterist Radio",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2020/02/scooterist-radio-ska-soul.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://listen.radioking.com/radio/214267/stream/257398",
            active: false,
        },
        {
            name:"Pelagatos Radio Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/pelagatos-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://buecrplb01.cienradios.com.ar/pelagatos.mp3",
            active: false,
        },
        {
            name:"Radio Te Amo Tropical",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2020/02/radio-te-amo-tropical-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radioteamotropical-radiofelove.radioca.st/stream",
            active: false,
        },
        {
            name:"Mashup Reggae",
            artist: "Reggae",
            cover: "https://manuappshome.files.wordpress.com/2019/09/mashup-reggae.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ais-edge37-live365-dal02.cdnstream.com/a00564",
            active: false,
        },
        {
            name:"Public Health Radio",
            artist: "Ska Music",
            cover: "https://manuappshome.files.wordpress.com/2020/02/public-health-radio-ska.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://publichealthradio.ice.infomaniak.ch/publichealthradio-192.mp3",
            active: false,
        },
    ];
}

export default chillHop;

